spring:
  profiles:
    active: local
    
  batch:
    job:
      names: ${job.name:NONE}


---

spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_basic_batch?useUnicode=true&characterEncoding=utf-8
    username: yshss1
    password: test1
    driver-class-name: org.mariadb.jdbc.Driver
