spring:
  profiles:
    active: local
    
  batch:
    job:
      names: ${job.name:NONE}
      
  jpa:
    hibernate:
      ddl-auto: none
    properties:
       hibernate:
#         show_sql: true
         '[format_sql]': true
  main:
    allow-bean-definition-overriding: true    

logging:
  level:
    '[org.springframework.batch]': DEBUG
    '[org.hibernate.SQL]': debug
    '[org.hibernate.type]': trace

---

spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_basic_batch?useUnicode=true&characterEncoding=utf-8
    username: yshss1
    password: test1
    driver-class-name: org.mariadb.jdbc.Driver
